name: Deploy to web server
on:
  push:
    branches: [deploy]
  
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    
    - name: Use node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
      
    - name: Build project
      run: |
        npm install
        yarn run build
    
    - name: List build files
      run: find build/ -print
    
    - name: Deploy to server
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.SFTP_USER }}
        username: ${{ secrets.SFTP_HOSTNAME }}
        password: ${{ secrets.SFTP_PASS }}
        port: 22
        protocol: ftps
        local-dir: 'build'
        server-dir: ${{ secrets.SFTP_TARGET_PATH }}
